### ISSUE TITLE
Cannot see Mod Manager

### ISSUE THREAD

**Issue by yangsibai** [Mrmaxmeier/BombSquad-Community-Mod-Manager#10]
I have installed Mod Manager, but I can't see it in the settings.

![2016-06-02 23 26 51 2](https://cloud.githubusercontent.com/assets/2907211/15765719/61feb7a8-296a-11e6-8803-923a335d7b2a.png)

My BombSquad version is 1.4.81.

**Comment by Mrmaxmeier** [comment]
Are you running BombSquad on Android M?
It recently switched to the new permission model on Android M.
Per default the app doesn't request the `storage` permission.
You can trigger the permission check by clicking on `Settings > Advanced > Show Mods Folder` or enable it manually in the `Android Settings > Apps > BombSquad > Permissions > Storage`.
If allowed BombSquad will load the mods on the next restart.

**Comment by yangsibai** [comment]
I'm running it on OS X 10.11.5 and I download it from Mac App Store.

My language is setting to Simple-Chinese. Does this matter?

**Comment by Mrmaxmeier** [comment]
The language setting shouldn't make a difference.
Does you mod folder contain the `installer.py` file or the mod manager files?
When the installation runs successfully the `installer.py` file should be gone.
If the file still exists: Do you get any screen messages about the installation?

**Comment by yangsibai** [comment]
After many times of restart. It's ok now.I think it's because of my bad network.

I'm playing and forget to reply. :P.

Thank you for your help. @Mrmaxmeier

**Comment by bombsquader** [comment]
My mods wont work i have bombsquad version 1.8.126
