### ISSUE TITLE
API version updated to 4

### ISSUE THREAD

**Issue by ghost** [Mrmaxmeier/BombSquad-Community-Mod-Manager#15]
Recently Froemling updated the API version to 4. Hence mods update is needed

**Comment by GnidGnaw** [comment]
I have already updated the mods to API version 4 in my repo. Most of the files are fully functional, but there are still a few that need further fixing.

**Comment by nktnet** [comment]
I can't find the mod manager in settings after the update. :(

**Comment by SoK05** [comment]
I edited the minigames scripts etc, maybe Mrmaxmeier will accept this changes :)

**Comment by Mrmaxmeier** [comment]
I've updated the gametypes and the mod manager to API v4.
The different gametypes are fully compatible so no change was needed.
You'll have to reinstall the mod manager though because it crashes before updating itself :/

**Comment by nktnet** [comment]
I see.....
Thank you so much :+1:

**Comment by TheSector120** [comment]
Hello,
I am very interested in the game modes and new characters and maps. I want to contribute to creating new characters , but I need to know the plugin I was used to create the characters.
I would also like to implement everything in the android devices. Here is a sample game that believes everything that you show : https://www.youtube.com/watch?v=gvAenDmRIxE&feature=gp-n-y&google_comment_id=z13qsx0q3mnbf5yb404cjpobwovoyj3gntc0k

Adradeceria to answer me .
Greetings.

**Comment by GnidGnaw** [comment]
The plugin that we used is for blender and you can find it under /utils/blender make sure to read the README file first. As for importing to android, the custom textures have to be compressed to .ktx, I personally use Mali compressor

**Comment by TheSector120** [comment]
I use Mali Compressor to put in textures android, but when I open the game appears to me in black textures.

**Comment by GnidGnaw** [comment]
The compression type has to be ETC2, and make sure that you check the box to enable mipmaps

**Comment by SoK05** [comment]
I appreciate the fact that more and more people wants to mod BombSquad :)

**Comment by nktnet** [comment]
Is it possible to add powerups as a mod? (e.g a bat for hitting bombs or used as a melee weapon).

**Comment by SoKpl** [comment]
New bombs are currently added to the BombSquad Joyride Modpack.

13 wrz 2016 13:15 "Nktnet" <notifications@github.com> napisał(a):

**Comment by TheMikirog** [comment]
https://bombsquadjoyride.blogspot.com/2016/09/brazil-stole-our-work.html
**# TheSector120**
Why you added our stuff without permission?
That's really pissing me off that you credited us, but you didn't added the link to our modpack.
It just discourages me to make more stuff.
We can team up, so you can develop the Joyride Modpack with me.
Just please don't rip me off...
https://bombsquadjoyride.blogspot.com/

**Comment by vagishjain** [comment]
Want to play this modpack in android but can't convert all the files. Help me guys.

**Comment by TheMikirog** [comment]
I'm working on how to create an APK. Stay tuned.
