### ISSUE TITLE
Game should end if opponent team is empty due to leaving the match

### ISSUE THREAD

**Issue by KishorJena** [Mrmaxmeier/BombSquad-Community-Mod-Manager#20]
When players leave match and no players are available in opponent team. game should be ended. But In super smash, game is not ending until time expires. Please fix this issue.

**Comment by Mrmaxmeier** [comment]
I've fixed it in https://github.com/Mrmaxmeier/BombSquad-Community-Mod-Manager/commit/86072bfdadbd9205f897396825a8104fe2cbb630
