### ISSUE TITLE
Server Mods

### ISSUE THREAD

**Issue by Avamander** [Mrmaxmeier/BombSquad-Community-Mod-Manager#30]
Has anyone here worked on or could share their results on what neat modifications they have made to the server (administrative utilities, custom playlists, etc.)? 

Another thing I have been thinking is that would it be possible to add a function to the mod manager to export the playlist in json so that it could be imported to the server?

**Comment by xiaoyuan1018** [comment]
分享自己的播放列表吗

**Comment by Avamander** [comment]
The server requires the playlist ID or the json of the playlist if I understood your sentence correct with Google Translate.

**Comment by Mrmaxmeier** [comment]
@Avamander I tried inserting a playlist by modifying the `config.json` but it looks like the server doesn't read the `"Free-for-All Playlist Selection"` property.
I haven't looked into other ways to manipulate the playlist because the official way using the `playlistCode` config setting works fine and is pretty convenient.

**Comment by Avamander** [comment]
Have you in any case figured out how to list all players and then based on that kick or start votekick?

Also, how to get a playlist ID?

**Comment by Mrmaxmeier** [comment]
You can get the playlist code by clicking share inside of the 'Customize Playlist' window.

I could try to build something on top of `bsInternal._getGameRoster` and `bsInternal._disconnectClient` similar to the in-game chat UI. It seems like the server code isn't really set up for interactions though.

**Comment by Avamander** [comment]
In-game controls to manage the server would be nice indeed. Though doesn't the server execute some commands and wouldn't that give the ability to add some kind of interactions?

**Comment by shekeling** [comment]
any news here? :)

**Comment by Awesome-Logic** [comment]
Well, I use chat commands.
chat commands work great for these kind of server managements.
I have made commands for kick/ban/reboot/change-playlist etc.
