### ISSUE TITLE
Model loading problem

### ISSUE THREAD

**Issue by xiaoyuan1018** [Mrmaxmeier/BombSquad-Community-Mod-Manager#32]
Is there a way to load a map model into the MODS directory?

**Comment by xiaoyuan1018** [comment]
And textures

**Comment by Mrmaxmeier** [comment]
Unfortunately this is not possible because the engine will only ever search for textures and models in `data/textures` and `data/models`.

**Comment by spdv123** [comment]
Well, I've found a way to accomplish that, you can view [BombSquad-Map-Installer](https://github.com/spdv123/BombSquad-Map-Installer) for more details. @Mrmaxmeier @xiaoyuan1018
