### ISSUE TITLE
Wanna Contribute!

### ISSUE THREAD

**Issue by abhinaypandey02** [Mrmaxmeier/BombSquad-Community-Mod-Manager#34]
I also want to contribute to the modpack please help anyone!!!
I have made a cool mod!

**Comment by TheMikirog** [comment]
This is not the place to do it. Send me an email (check my GitHub profile), show me your idea, give some screenshots, maybe gameplay, etc. Please remember I only accept quality mods that take EFFORT to create. Not random edits of existing mods. That's lazy. [Here's what I DO NOT accept for JRMP.](https://bombsquadjoyride.blogspot.com/2017/05/future-updates-might-get-worse-thanks.html) Use that as a guideline.

**Comment by Froshlee14** [comment]
Hi there, Im wanna contribute to the Mod manager with a tittle mod, but I dont know where send it!!
What should I do?
