### ISSUE TITLE
How to change .bob files

### ISSUE THREAD

**Issue by abhinaypandey02** [Mrmaxmeier/BombSquad-Community-Mod-Manager#35]
I really feel like making new maps with blender or editing the previous but .bob file extension is a problem which software can access it please tell anyone!

**Comment by TheMikirog** [comment]
If you took some time and actually explore this site for a little bit, you'll find BOB File Export addon for Blender made by Mrmaxmeier using the source code I delivered straight from Eric Froemling himself. It supports UV Meshes, automatic triangulation and Level Collider Meshes (.COB).

**Comment by yash2879** [comment]
where is the actual file download button

**Comment by Mrmaxmeier** [comment]
[Here is a tiny tutorial on how to use the Blender plugin](https://github.com/Mrmaxmeier/BombSquad-Community-Mod-Manager/tree/master/utils/blender).
