### ISSUE TITLE
Texture??

### ISSUE THREAD

**Issue by CerdoGordo** [Mrmaxmeier/BombSquad-Community-Mod-Manager#37]
hi, I want to create a map, but when im export, the map is Black!! That I have to do?? Tks, i wait answer!!

**Comment by Mrmaxmeier** [comment]
Hey,

all of the models in BombSquad generally have a `.dds` texture file associated with them.
The `HockeyStadium` map for instance uses `hockeyStadiumInner.bob` and `hockeyStadiumOuter.bob` as models that both share the texture file `hockeyStadium.dds`.

This information is defined in the map definition; here is the relevant snippet taken from `bsMap.py`:
```python
data['models'] = (bs.getModel('hockeyStadiumOuter'),
                  bs.getModel('hockeyStadiumInner'))
data['tex'] = bs.getTexture('hockeyStadium')
```
If the BombSquad engine fails to load the texture file (if the file doesn't exist or is corrupted) the model will appear black. In your case the texture file is probably missing.
