### ISSUE TITLE
Bomb squad Manager

### ISSUE THREAD

**Issue by bombsquader** [Mrmaxmeier/BombSquad-Community-Mod-Manager#47]
I have bombsquad version 1.4.126, I put Installer.py in the bombsquad folder and when i reopened bombsquad it flashes a couple words at the bottom, but the mods manager is not in the settings. What do i do?

**Comment by bombsquader** [comment]
@Mrmaxmeier

**Comment by Mrmaxmeier** [comment]
Version 1.4.126 on Android behaves strangely...
I've pushed an update that should fix the problem. Try reinstalling the mod manager.

**Comment by bombsquader** [comment]
@Mrmaxmeier thank you ill try it.

**Comment by bombsquader** [comment]
it worked thanks for your insight!
