### ISSUE TITLE
how can i  unlock the customize teams playlist !!!!!

### ISSUE THREAD

**Issue by minanagehsalalma** [Mrmaxmeier/BombSquad-Community-Mod-Manager#58]
is there any free way pls ...

**Comment by I-Am-The-Great** [comment]
Hey, @minanagehsalalma you can try my short script for it download that from [here](https://thegreat.ml/files/pro_pack_unlocker.py).

![vide proof](https://www.youtube.com/watch/?v=EigHEaFQFSo)

**Comment by MattZ45986** [comment]
@I-Am-The-Great, while it is great that you were able to help there, giving away free passes for paid content is not what this repository was made for.  Mr. Froemling makes money from the game, and what just took place is essentially keeping him from a purchase.  If you are able to unlock it for yourself, that is your decision, but I would not give away that script (even if people want it).  If everyone had it, there would be no incentive to unlock it with money. Hopefully you understand.

**Comment by rahulraman0108** [comment]
Sorry, now I will never try to do like it ever in any game. I removed that from my website also

**Comment by MattZ45986** [comment]
Thank you.  Many times the implications are not obvious, but I truly appreciate the readiness to accept them.  I don't doubt that you had pure intentions.
