### ISSUE TITLE
How to export material and textures from blender

### ISSUE THREAD

**Issue by rahulraman0108** [Mrmaxmeier/BombSquad-Community-Mod-Manager#60]

**Comment by rahulraman0108** [comment]
please say how can i export materials and textures of models made in blender as images to create character textures.

**Comment by MattZ45986** [comment]
In Blender you should make the character and UV map the image you want on to the character model pieces.  The model in-game will use the texture to create a character.  Essentially, create a texture image that includes all of the different angles needed for coloring the character.  Then, export the 3D models with the UV map data and texture to put it in the 'models' and 'textures' folders in the main Bombsquad file.  Finally, in Spaz.py set up the new character with the texture you made.  If you need an example just look at the textures in the 'textures' file.  (In Spaz.py you assign the texture the character will use.)

**Comment by rahulraman0108** [comment]
I made a wolverine character, I posted its video on youtube here is [video link](https://www.youtube.com/watch?v=U0wiV9qUI08&t=4s ).

**Comment by MattZ45986** [comment]
That's pretty cool, I guess you figured it out then.  Let me know if you need any more help.
