### ISSUE TITLE
I am going to share this repository's mods from my repository

### ISSUE THREAD

**Issue by rahulraman0108** [Mrmaxmeier/BombSquad-Community-Mod-Manager#68]
Respected sirs,
I am creating a BombSquad dedicated server and in that, I will use this repository's mods, but I will also make a github repository to share my server's files so, the repository will also include the mods taken from here. As this repository has `The Unlicense` license, I think that it will not be any illegal or wrong work to add mods from this repository to my repository, but yet I ask to not let any confusion bother me.

May I add the mods from this repository to my repository or not?

**Comment by Mrmaxmeier** [comment]
Yup. Feel free to copy the mods over to your repo.
If you want you, can also link back to this repository somewhere in your project (:

**Comment by rahulraman0108** [comment]
Okay, thank you.
