### ISSUE TITLE
how i can use this mod games in server ?

### ISSUE THREAD

**Issue by Teals53** [Mrmaxmeier/BombSquad-Community-Mod-Manager#71]

**Comment by rahulraman0108** [comment]
@Teals53 
_**You should have added a correct description to your issue though this issue's title may explain what you mean to say but it is better to have a short title with a good description of the issue.**_
And to the answer of your question:
1. You need to download the game's script and put it in mods folder on both: 
    1) the device on which you make and export playlist, and,
    2) the server of your BombSquad party
2. Make a playlist with the new game added to it then export it and write down the sharing code.
3. In the `bombsquad_server` file on the server of your BombSquad party write the playlist sharing code in the option : `config["playlistCode"]`

**And you are done, run the server and the server will have the game you added.**

**Comment by Teals53** [comment]
i already do this but its not work im using server files for windows not for local one .d

**Comment by rahulraman0108** [comment]
Uhm, can you please explain which part is not working. And what do you mean by server files for local one?

**Comment by Teals53** [comment]
![image](https://user-images.githubusercontent.com/13446881/63214715-8708e000-c124-11e9-921a-ae0cba30f76f.png)
i open server there

**Comment by Teals53** [comment]
my mods are ready
![image](https://user-images.githubusercontent.com/13446881/63214721-99831980-c124-11e9-82b6-358cb8720ecf.png)

**Comment by Teals53** [comment]
and my custom playlist ready too
![image](https://user-images.githubusercontent.com/13446881/63214725-a4d64500-c124-11e9-807b-17bd6801da05.png)

**Comment by Teals53** [comment]
then i share this and put code there
![image](https://user-images.githubusercontent.com/13446881/63214729-bae40580-c124-11e9-804b-364efb922c7b.png)

**Comment by Teals53** [comment]
and i open server and join but still just play offical games not mods games

**Comment by Teals53** [comment]
i can play my custom playlist but server cant play mods games idk why and i want help about that 

thx

**Comment by rahulraman0108** [comment]
@Teals53 have you added the games mods to `<server files location>\data\scripts\` folder?

**Comment by Teals53** [comment]
oh yeah u r right i forgot that thx dude

**Comment by rahulraman0108** [comment]
It's good that you found the solution of your issue at last, now you should close this issue, and remember to put a short title with a good description in your new issues.

**Comment by Teals53** [comment]
kk dude thx for help cy@
